# Generated by Django 4.2.7 on 2023-11-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('sinopsis', models.TextField()),
                ('created_at', models.TextField()),
                ('update_at', models.TextField()),
            ],
        ),
    ]
